import { createContext, useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import SearchBar from "../components/searchBar/SearchBar";
import OutputPosts from "../components/outputPosts/OutputPosts";
import { PostsFromQuery } from "../server/trpc/router/postsByTags";
// will create context to flow the data between search, tags box, and featred posts to outputPosts without passing props
export type OutputPostsContextState = [
  posts:PostsFromQuery,
  setPosts: (posts: PostsFromQuery) => void
];
export const OutputPostsContext = createContext<OutputPostsContextState>([[], (posts) => { return; }])
const Home: NextPage = () => {
  const outputPosts = useState<PostsFromQuery>([]);
  return (
    <>
      <Head>
        <title>Zagy-Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1>If you want to write something open a pull request here <a href="https://github.com/The-Zagy/zagy-blog/tree/main/content/blog" className="dark:text-dark-secondary-500 text-dark-primary-700">Github</a></h1>
        <OutputPostsContext.Provider value={outputPosts}>
        <SearchBar />
        <OutputPosts />
        </OutputPostsContext.Provider>
      </main>
    </>
  );
};

export default Home;
